version: "3.9"
services:
  db:
    image: postgres
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: dev
